apiVersion: v1
kind: ConfigMap
data:
  sensitive.properties: |
    test1.sensitive:{v3.0.3:base64_encoded_value}7IaHlHKpe34sV5s8bPAB6Q==
    test3.sensitive:{v3.0.3:base64_encoded_value}7a6l0VH7B3odBa0HHKBwpg==
    test2.sensitive:{v3.0.3:base64_encoded_value}DiWtONBUnnThmaCtKeytKg==
    test4.sensitive:{v3.0.3:base64_encoded_value}YPZKMKavqSQxqGedyrPPK2/DLcb9FCVOm3VHFZ1iYhvUD2wUsjGrnI85RhApHNmL
    test5.sensitive:{v3.0.3:base64_encoded_value}EIeFaKZHPblwnjKwXNegUqBcZcQSZpg8XNbDCgvbJ9ryBGW0puMI82+hufEeCVYgWwLLXKv75qhNY2+MlYP/ZQ==
metadata:
  name: sensitive
  namespace: default