apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: common-digi
  name: common-digi
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: common-digi
  type: ClusterIP
status:
  loadBalancer: {}
